rules:
  - id: js-no-dynamic-code-execution
    message: Avoid dynamic code execution (`eval`/`Function`).
    severity: ERROR
    languages:
      - javascript
      - typescript
    patterns:
      - pattern-either:
          - pattern: eval(...)
          - pattern: new Function(...)
