rules:
  - id: python-no-subprocess-shell-true
    message: Do not use shell=True with subprocess; invoke commands as argument lists.
    severity: ERROR
    languages:
      - python
    patterns:
      - pattern-either:
          - pattern: subprocess.run(..., shell=True, ...)
          - pattern: subprocess.Popen(..., shell=True, ...)
          - pattern: subprocess.call(..., shell=True, ...)
          - pattern: subprocess.check_call(..., shell=True, ...)
          - pattern: subprocess.check_output(..., shell=True, ...)

  - id: python-no-weak-hash-primitives
    message: Avoid MD5/SHA1 in runtime code; use SHA-256 or stronger primitives.
    severity: ERROR
    languages:
      - python
    patterns:
      - pattern-either:
          - pattern: hashlib.md5(...)
          - pattern: hashlib.sha1(...)

  - id: python-jwt-no-signature-bypass
    message: Never disable JWT signature verification.
    severity: ERROR
    languages:
      - python
    patterns:
      - pattern: 'jwt.decode(..., options={..., "verify_signature": False, ...}, ...)'

  - id: js-no-dynamic-code-execution
    message: Avoid dynamic code execution (`eval`/`Function`).
    severity: ERROR
    languages:
      - javascript
      - typescript
    patterns:
      - pattern-either:
          - pattern: eval(...)
          - pattern: new Function(...)
